### ISSUE TITLE
Check link checker

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshop#11]
I doubt the CI script to check links, as it has never failed. Fix it!

**Comment by richelbilderbeek** [comment]
Indeed, it does not check links at all:

![Screenshot from 2023-12-12 09-48-49](https://github.com/UPPMAX/bianca_workshop/assets/2098230/ffe211cd-9fcd-4907-81b6-2997bb40785d)

**Comment by richelbilderbeek** [comment]
When installing tool behind it:

```
sudo npm install -g markdown-link-check
```

then using it (as copy-paste from the CI script):

then

```
find . -name '*.md' -not -path './node_modules/*' -exec markdown-link-check '{}' --config mlc_config.json -v ';'
```

I get a solid hint:

```
FILE: ./docs/linux.md
undefined:3
    "ignorePatterns": [
    ^

SyntaxError: Unexpected string in JSON at position 68
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:125:34)
    at ReadStream.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by richelbilderbeek** [comment]
Solution is [in the diff](https://github.com/UPPMAX/bianca_workshop/commit/a2966ce4fd67245f4fa0e035c7cafae02b2da8d0): there was a comma missing in `mlc_config.json`

**Comment by richelbilderbeek** [comment]
The file `reflections/README.md` has broken links put in on purpose. As long as these are not detected, the link checker is overlooking things :-)
